version: '3'
services:
  opensearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Francis198!!!"
      - plugins.security.ssl.http.enabled=true
      - plugins.security.ssl.transport.enabled=true
      - plugins.security.allow_unsafe_democertificates=true
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./opensearch-config/analysis/warhammer_dict.txt:/usr/share/opensearch/config/analysis/warhammer_dict.txt
      - ./opensearch-config/analysis/warhammer_synonyms.txt:/usr/share/opensearch/config/analysis/warhammer_synonyms.txt
      - ./opensearch-config/analysis-ik/IKAnalyzer.cfg.xml:/usr/share/opensearch/config/analysis-ik/IKAnalyzer.cfg.xml
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9600:9600"
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.1.0
    container_name: opensearch-dashboards
    ports:
      - "127.0.0.1:5601:5601"
    expose:
      - '5601'
    environment:
      - OPENSEARCH_HOSTS=https://opensearch:9200
      - I18N_LOCALE=en
      - I18N_USE_LEGACY_I18N=false
      - OPENSEARCH_DASHBOARDS_SERVER_DEFAULTROUTE=/app/home
    networks:
      - opensearch-net
    depends_on:
      - opensearch

volumes:
  opensearch-data:

networks:
  opensearch-net:
    driver: bridge