# ===================== 数据路径配置 =====================
intent_data_path: intent_training/data/raw/intent_sample.csv   # 意图识别数据CSV路径
slot_data_path: intent_training/data/raw/slot_sample.conll     # 槽位填充数据CoNLL路径

# ===================== 数据切分参数 =====================
test_size: 0.2        # 测试集占比，0~1之间小数
val_size: 0.1         # 验证集占比，0~1之间小数
random_state: 42      # 随机种子，保证实验可复现
stratify: true        # 是否分层抽样，true/false
min_query_length: 3   # 查询最小长度，过滤过短无效数据
max_query_length: 200 # 查询最大长度，过滤过长异常数据
min_sentence_length: 2   # 槽位句子最小长度
max_sentence_length: 100 # 槽位句子最大长度

# ===================== 特征工程参数 =====================
intent_feature:
  max_features: 1000  # TF-IDF最大特征数
  ngram_range: [1, 2] # ngram范围，(1,2)表示1-2gram
  min_df: 1           # 最小文档频率，过滤低频特征
  analyzer: char      # 分析粒度，char=字符级，word=词级
  intent_tfidf: intent_tfidf.pkl  # TF-IDF特征提取器文件名

slot_feature:
  max_features: 1000  # 槽位特征最大数
  ngram_range: [1, 2] # 槽位特征ngram范围

# ===================== 模型文件名配置 =====================
model:
  intent_classifier: intent_classifier.pkl  # 意图分类器模型文件名
  sequence_slot_filler: sequence_slot_filler.pkl  # 序列槽位填充器模型文件名

# ===================== 分类器参数 =====================
classifier_type: logistic   # 分类器类型，可选logistic/svm/random_forest
max_iter: 1000              # 最大迭代次数
n_estimators: 100           # 随机森林树数

slot_buffer_max_size: 1000  # 槽位缓存最大长度
slot_classifier_type: logistic # 槽位分类器类型
slot_classifier_max_iter: 200  # 槽位分类器最大迭代次数

# ===================== 模型导出与评估 =====================
model_output_dir: intent_training/model_output/   # 统一的模型产出目录，训练、评估、导出、上线全流程共用
report_path: intent_training/report/        # 评估报告保存路径

# ===================== 不确定性与解释性参数 =====================
uncertainty:
  review_threshold: 0.5     # 人工审核阈值，超过则需人工复核
  auto_confidence_threshold: 0.85  # 自动信任阈值，高于此值自动通过
  methods: [entropy, confidence, margin]  # 不确定性计算方法
  combined_weight:          # 各方法权重，和为1
    entropy: 0.4            # 熵方法权重
    confidence: 0.4         # 置信度方法权重
    margin: 0.2             # 边距方法权重
  buffer_max_size: 1000     # 不确定性查询缓存最大长度 

# 评估相关配置
evaluation:
  run_evaluation: true  # 是否在训练后执行评估流程的总开关
  export_threshold: 0.85  # 模型评估的质量门槛，frame_accuracy 必须高于此值模型才会被导出
  summary_report_path: "document/evaluation_summary.md"  # 摘要报告的输出路径
  detailed_report_path: "document/evaluation_detailed.json"  # 详细报告的输出路径 